### ISSUE TITLE
Window style choice

### ISSUE THREAD

**Issue by housemacgill** [houseproject/addition#1]
Clip in - cheapest - will break - easy to clean
in glass - more expensive - longer to make - can impact energy efficiency
SDL - cost unknown - delivery time unknown

**Comment by jrmacgill** [comment]
White exterior/white interior no grilles $12,460.64
White exterior/white interior SDL grilles $16,808.61
In glass - $13,700 - no impact on energy efficiency.

**Comment by jrmacgill** [comment]
Decision is between glass - top half only.

**Comment by cutabovenj** [comment]
ok and the casement windows and sliding door will have full grilles as theres no option for top pane only being one piece of glass.

**Comment by jrmacgill** [comment]
Just realized - I don't think you have the three small basement windows in your set.

**Comment by cutabovenj** [comment]
Are the basement windows vinyl now? I didn't include basement windows and if we replace them we would typically use a vinyl window.

**Comment by jrmacgill** [comment]
Just checked - one is old and wood - the others are vinyl and probably fine
(one is damaged but it is the one that will be removed at the rear anyway).

So - yes it would be good to replace the one old wooden one with a vinyl
one.

**Comment by cutabovenj** [comment]
No problem. A vinyl basement window is $300 labor and material. I will measure tomorrow and place the order. Any change orders will be typed up and sent to you for your records. They would need to be signed and paid in full at time of signing. (or have thew bank mail me a check within a week is ok too.)

**Comment by jrmacgill** [comment]
[MacGill Final Window List.pdf](https://github.com/houseproject/addition/files/777949/MacGill.Final.Window.List.pdf)

**Comment by housemacgill** [comment]
How much would frosting be on the bathroom windows?

**Comment by jrmacgill** [comment]
Frost new bathroom oval window only.
Good to order.

**Comment by housemacgill** [comment]
(sorry, quick follow up - you mentioned something about a crank to open
lower bathroom window - would that get in the way of instlling a blind at
that window?)

**Comment by cutabovenj** [comment]
Casement windows usually can have an inside mount blind. Fairly common. Gets mounted to the top of window frame.

**Comment by jrmacgill** [comment]
OK - chatted with Linda I gather frosting the oval is not possible.

**Comment by jrmacgill** [comment]
No frosting on any windows - good to order (again).
