### ISSUE TITLE
Garage Repair / Door

### ISSUE THREAD

**Issue by jrmacgill** [houseproject/addition#10]
The garage has had a broken post for a long time on the right side - before we get siding on the garage can you get someone to fix it?

We should also look at getting a new garage door and opener

**Comment by cutabovenj** [comment]
Yes I will take a look and get it fixed this week.
You can take a look here and let me know which doors you like so I can get pricing.
https://www.clopaydoor.com/residential-garage-doors

**Comment by jrmacgill** [comment]
Clopay classic with short panels:
https://www.clopaydoor.com/classic#Designs

Can you price with the top row as colonial windows - and also for the different construction strengths.

**Comment by jrmacgill** [comment]
Looks like garage repair is starting to hold up the siding work.

**Comment by cutabovenj** [comment]
My siding guys are doing the repair. He does framing also. I spoke with him early last week about this.

**Comment by jrmacgill** [comment]
On Wed, Apr 12, 2017 at 9:47 AM, cutabovenj <notifications@github.com>
wrote:

> My siding guys are doing the repair. He does framing also. I spoke with
> him early last week about this.
>
Oh good to know they are on top of it.  Thanks.


>
> Sent from my iPhone 6
>

**Comment by cutabovenj** [comment]
Garage repair was done today.
I will be there to inspect it tomorrow.

Thank you,
Blaine Shofner
Cut Above Renovations LLC
201-212-0578
www.cutabovenj.com
