### ISSUE TITLE
No smoking in or next to the house

### ISSUE THREAD

**Issue by foxyoxy** [houseproject/addition#13]
If everybody could be asked politely not to smoke in the unfinished parts of the house or near the doorways, I would appreciate it. The end of the driveway / yard is fine. While the plumbers were in the kitchen just now and I was in the basement, I could smell it really strongly (no ceiling!) and, to somebody who doesn't smoke, it really stinks. I have asked one of the plumbers directly to stop but would appreciate it if everybody else did the same. Thanks.

**Comment by jrmacgill** [comment]
Resolved.
