### ISSUE TITLE
Dining room / Kitchen opening size.

### ISSUE THREAD

**Issue by jrmacgill** [houseproject/addition#4]
Plans had this at 5 ft for pocket door.  Now that we are not going for a pocket door can the opening be larger?  

What style will the opening be?

**Comment by cutabovenj** [comment]
This would be a question for Tim Klesse. He would have to write a letter confirming a wider size.

**Comment by jrmacgill** [comment]
Having seen the potential kitchen layout - we have the room we need and don't need the gap to be larger - the marked ~5ft is fine.

Open question on styling of the arch - other arch into dining room is curved at top, would be good if they matched (both square or both curved would be fine).

**Comment by cutabovenj** [comment]
We budgeted in just a square opening. We would have to reframe the existing one. Or we could reframe the new one to have an arch. Framing an arch would be more expensive though.
Yes, I spoke to Kathy already about window changes and sent in a revised window list to my distributer. 

Thank you,
Blaine Shofner
Cut Above Renovations LLC
201-212-0578
www.cutabovenj.com

**Comment by jrmacgill** [comment]
Square will work - would be nice to square off and frame the currently rounded arches either side of the front door so that they all match.

**Comment by jrmacgill** [comment]
On Tue, Feb 14, 2017 at 2:12 PM, cutabovenj <notifications@github.com>
wrote:

> We budgeted in just a square opening. We would have to reframe the
> existing one. Or we could reframe the new one to have an arch. Framing an
> arch would be more expensive though.
> Yes, I spoke to Kathy already about window changes and sent in a revised
> window list to my distributer.
>

Just looked at the framing work that was done today and the holes for the
windows in the kitchen match the initial positions not the revised single
larger window.


>
> Thank you,
> Blaine Shofner
> Cut Above Renovations LLC
> 201-212-0578 <(201)%20212-0578>
> www.cutabovenj.com
>
>
>
>
