### ISSUE TITLE
Maze of doors

### ISSUE THREAD

**Issue by jrmacgill** [houseproject/addition#5]
The area outside the downstairs bathroom is currently a maze of doors - we want to open up that space but without making it feel like the bathroom opens into the kitchen.

Meeting with kitchen designer tomorrow - will work out if space can be used as storage from kitchen side or if should be walled to just make an area outside the bathroom that is separate from the kitchen.

**Comment by jrmacgill** [comment]
Decision is to not make this part of the kitchen - but still to remove the two cupboards to make it less cramped.

**Comment by jrmacgill** [comment]
After kitchen design meeting - please keep the wall / door between the kitchen and the area outside the downstairs bathroom.  We still want to loose the two cupboards outside that bathroom but we do not want that area merged with the kitchen.

**Comment by jrmacgill** [comment]
Wall to kitchen may end up removed and then re-built later in construction work.

**Comment by cutabovenj** [comment]
Yes better to remove drywall and wall to install new structure. We will then build a new wall and you have an option to install soundproof insulation and drywall on wall between kitchen and existing bathroom. 
Your wife didn't seem thrilled about the vr lol.
