### ISSUE TITLE
'Seat' in shower area

### ISSUE THREAD

**Issue by jrmacgill** [houseproject/addition#6]
The area marked 'seat' in the shower is an odd use of the space - is it possible to flip this into Benjamin's bedroom (front) for use as shelving?

**Comment by cutabovenj** [comment]
This will have to be determined once wall framing starts as this wall is a point load for structure. If we move the wall there is no load support in the existing first floor ceiling. I will keep you posted on this as framing continues.

**Comment by jrmacgill** [comment]
Framing seems to be well underway - can we take a look at this again?

**Comment by cutabovenj** [comment]
Ill be by the hopuse tomorrow and will take a look and figure out the best shower layout.

Thank you,
Blaine Shofner
Cut Above Renovations LLC
201-212-0578
www.cutabovenj.com

**Comment by jrmacgill** [comment]
Thanks.
