### ISSUE TITLE
Choose siding tint

### ISSUE THREAD

**Issue by jrmacgill** [houseproject/addition#8]
http://www.royalbuildingproducts.com/siding/products/traditional-siding/royal-crest/

**Comment by jrmacgill** [comment]
Specfially from this page:
http://www.gaf.com/Roofing/Residential/Products/Shingles/Timberline/High_Definition

**Comment by jrmacgill** [comment]
We will go with white.

**Comment by jrmacgill** [comment]
Which 'profile' are you using?

**Comment by cutabovenj** [comment]
clapboard is much more popular these days but if you like the dutchlap we can do that. Most people do go clapboard though. Let me know as I want to get my siding guys in as soon as the windows are delivered. Windows should be delivered the 20-21st.

**Comment by jrmacgill** [comment]
Happy to go with the profile that fits with the area - which seems to be clapboard.

Out of curiosity I see 'crest' is the cheapest of their options, what does going up the scale in products do the price and durability of the siding?

**Comment by cutabovenj** [comment]
Vinyl siding goes up in price the thicker the vinyl. If you wanted to upgrade to a higher level vinyl the cost would be in the $1350-1500 range.

Thank you,
Blaine Shofner
Cut Above Renovations LLC
201-212-0578
www.cutabovenj.com

**Comment by jrmacgill** [comment]
Current schedule has "Upon start of siding $17,000" - whats the incremental cost - all the way up to the insulated options (haven?)

**Comment by cutabovenj** [comment]
I would have to get an exact price for that. Only the material cost changes. The labor stays the same for all plank siding. 
I will let you know the exact price.
We will be starting the hvac this week. Can you have the bank send that check out please.

Thank you,
Blaine Shofner
Cut Above Renovations LLC
201-212-0578
www.cutabovenj.com

**Comment by cutabovenj** [comment]
Here are the siding prices:
Crest: included in original budget at basicv colors. Premium coors additional.
Estate: $900 additional
Woodland: $1350 additional 
Haven: (insulated panel) $5535 additional
Portsmouth shake: $5913 additional

Spoke to my hvac guy and although we have to install additional units, the price will stay on budget. He did mention the bedroom unit would have to be on the back wall or we could re frame the closet wall 12” deeper.

I was on site discussing the existing sewer stack (cast iron pipe in kitchen) and there is no way to move that into a wall cavity. We will have to box it in with framiong and sheetrock. 

Thank you,
Blaine Shofner
Cut Above Renovations LLC
201-212-0578
www.cutabovenj.com

**Comment by jrmacgill** [comment]
Thanks for the prices - will do some research and get back to you asap.

**Comment by jrmacgill** [comment]
resolved - Woodland clapboard white.
